# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: scheduled-event-exporter
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
# Archive customization
archive:
  format: tar.gz