language: go

go:
  - master

services:
  - docker

script:
  - true

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
  - CGO_ENABLED="0" GOARCH="amd64" GOOS="linux" go build -a -installsuffix cgo -o ./app
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=peakcom/scheduled-event-exporter
  - echo $REPO:$TRAVIS_BRANCH
  - docker build -f Dockerfile -t $REPO:$TRAVIS_BRANCH .
  - docker push $REPO:$TRAVIS_BRANCH
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
  - if [[ ! -z "${TAG}" ]]; then docker tag $REPO:$TRAVIS_BRANCH $REPO:$TAG; fi
  - if [[ ! -z "${TAG}" ]]; then docker push $REPO:$TAG; fi